"""Deterministic file inspection and chunk extraction for cloned repositories."""

from __future__ import annotations

import hashlib
import logging
import re
import sqlite3
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterator

from .extraction_ast import ASTChunkSpec, extract_python_ast

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# File inclusion / exclusion rules
# ---------------------------------------------------------------------------

EXCLUDED_DIRS = {
    ".git",
    "node_modules",
    "vendor",
    "dist",
    "build",
    "target",
    ".next",
    ".venv",
    "venv",
    "env",
    ".env",
    "coverage",
    ".coverage",
    "__pycache__",
    ".mypy_cache",
    ".pytest_cache",
    ".tox",
    ".eggs",
    "*.egg-info",
    ".cache",
    "tmp",
    "temp",
}

EXCLUDED_EXTENSIONS = {
    # Compiled / binary
    ".pyc", ".pyo", ".pyd",
    ".so", ".dll", ".dylib", ".a", ".lib",
    ".o", ".obj",
    ".class", ".jar",
    ".wasm",
    # Assets
    ".png", ".jpg", ".jpeg", ".gif", ".bmp", ".ico", ".svg", ".webp",
    ".mp3", ".mp4", ".wav", ".ogg", ".avi", ".mov",
    ".ttf", ".woff", ".woff2", ".eot",
    ".pdf", ".doc", ".docx", ".xls", ".xlsx", ".ppt", ".pptx",
    # Archives
    ".zip", ".tar", ".gz", ".bz2", ".xz", ".7z", ".rar",
    ".whl", ".egg",
    # Minified / generated
    ".min.js", ".min.css", ".bundle.js", ".chunk.js",
    # Lock files (not useful for extraction)
    ".lock",
    # Database
    ".db", ".sqlite", ".sqlite3",
}

EXCLUDED_FILENAMES = {
    "package-lock.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "Pipfile.lock",
    "poetry.lock",
    "Gemfile.lock",
    "Cargo.lock",
    "composer.lock",
    ".DS_Store",
    "Thumbs.db",
}

# Extensions that are valuable to extract
INCLUDED_EXTENSIONS: dict[str, str] = {
    ".py": "python",
    ".js": "javascript",
    ".ts": "typescript",
    ".tsx": "typescript",
    ".jsx": "javascript",
    ".rs": "rust",
    ".go": "go",
    ".java": "java",
    ".kt": "kotlin",
    ".swift": "swift",
    ".rb": "ruby",
    ".php": "php",
    ".c": "c",
    ".cpp": "cpp",
    ".h": "c",
    ".hpp": "cpp",
    ".cs": "csharp",
    ".md": "markdown",
    ".rst": "rst",
    ".txt": "text",
    ".yml": "yaml",
    ".yaml": "yaml",
    ".toml": "toml",
    ".json": "json",
    ".sh": "shell",
    ".bash": "shell",
    ".zsh": "shell",
    ".fish": "shell",
    ".dockerfile": "dockerfile",
    ".tf": "terraform",
    ".hcl": "hcl",
    ".sql": "sql",
    ".graphql": "graphql",
    ".proto": "protobuf",
    ".xml": "xml",
    ".html": "html",
    ".css": "css",
    ".scss": "scss",
    ".sass": "scss",
}

# Special filenames that are valuable even without a matching extension
VALUABLE_FILENAMES = {
    "Dockerfile": "dockerfile",
    "Makefile": "makefile",
    "Rakefile": "ruby",
    "Gemfile": "ruby",
    "Pipfile": "toml",
    "pyproject.toml": "toml",
    "setup.cfg": "ini",
    "setup.py": "python",
    "CHANGELOG": "text",
    "CHANGELOG.md": "markdown",
    "README": "text",
    "README.md": "markdown",
    "LICENSE": "text",
    ".github": None,  # skip directory
}

# Max file size to attempt extraction (bytes)
MAX_FILE_BYTES = 500_000

# Byte length of header region to scan for generated-file markers
_GENERATED_HEADER_BYTES = 512

# Patterns that indicate machine-generated files (scan the first _GENERATED_HEADER_BYTES bytes)
_GENERATED_MARKERS: list[str] = [
    "DO NOT EDIT",
    "do not edit",
    "Do not edit",
    "Code generated",
    "code generated",
    "AUTO-GENERATED",
    "auto-generated",
    "Auto-generated",
    "autogenerated",
    "Autogenerated",
    "AUTOGENERATED",
    "This file is generated",
    "this file is generated",
    "Generated by",
    "generated by",
    "@generated",
    "# Generated",
    "// Generated",
    "/* Generated",
]


# ---------------------------------------------------------------------------
# Data structures
# ---------------------------------------------------------------------------

@dataclass
class FileRecord:
    relative_path: str
    language: str | None
    file_kind: str   # source, config, doc
    size_bytes: int
    line_count: int
    included: bool
    skip_reason: str | None


@dataclass
class Chunk:
    file_path: str       # relative path within repo
    language: str | None
    chunk_type: str      # class, function, method, section, file
    symbol_name: str | None
    start_line: int
    end_line: int
    content: str
    content_hash: str = field(default="")

    def __post_init__(self) -> None:
        if not self.content_hash:
            self.content_hash = hashlib.sha256(self.content.encode()).hexdigest()


# ---------------------------------------------------------------------------
# File inspection
# ---------------------------------------------------------------------------

def _is_excluded_dir(path_part: str) -> bool:
    return path_part in EXCLUDED_DIRS or path_part.endswith(".egg-info")


def inspect_repo_files(repo_path: Path) -> Iterator[FileRecord]:
    """Enumerate and classify all files in a cloned repo."""
    for file_path in repo_path.rglob("*"):
        if not file_path.is_file():
            continue

        # Check excluded directory components
        try:
            rel = file_path.relative_to(repo_path)
        except ValueError:
            continue

        parts = rel.parts
        if any(_is_excluded_dir(p) for p in parts[:-1]):
            continue

        filename = file_path.name
        suffix = file_path.suffix.lower()

        # Excluded filenames
        if filename in EXCLUDED_FILENAMES:
            yield FileRecord(
                relative_path=str(rel),
                language=None,
                file_kind="noise",
                size_bytes=0,
                line_count=0,
                included=False,
                skip_reason="excluded_filename",
            )
            continue

        # Excluded extensions
        if suffix in EXCLUDED_EXTENSIONS:
            yield FileRecord(
                relative_path=str(rel),
                language=None,
                file_kind="binary_or_noise",
                size_bytes=0,
                line_count=0,
                included=False,
                skip_reason="excluded_extension",
            )
            continue

        # Size check
        try:
            size = file_path.stat().st_size
        except OSError:
            yield FileRecord(
                relative_path=str(rel),
                language=None,
                file_kind="unknown",
                size_bytes=0,
                line_count=0,
                included=False,
                skip_reason="stat_error",
            )
            continue

        if size > MAX_FILE_BYTES:
            yield FileRecord(
                relative_path=str(rel),
                language=None,
                file_kind="oversized",
                size_bytes=size,
                line_count=0,
                included=False,
                skip_reason="file_too_large",
            )
            continue

        # Detect language
        language = INCLUDED_EXTENSIONS.get(suffix) or VALUABLE_FILENAMES.get(filename)
        if language is None:
            # Try by lowercase suffix match
            language = INCLUDED_EXTENSIONS.get(file_path.suffix)

        if language is None:
            yield FileRecord(
                relative_path=str(rel),
                language=None,
                file_kind="unknown",
                size_bytes=size,
                line_count=0,
                included=False,
                skip_reason="unsupported_type",
            )
            continue

        # Read and count lines, check for binary content
        try:
            text = file_path.read_text(encoding="utf-8", errors="replace")
            # Heuristic: if many null bytes, treat as binary
            if text.count("\x00") > len(text) * 0.01:
                yield FileRecord(
                    relative_path=str(rel),
                    language=None,
                    file_kind="binary",
                    size_bytes=size,
                    line_count=0,
                    included=False,
                    skip_reason="binary_content",
                )
                continue
            line_count = text.count("\n") + (1 if text and not text.endswith("\n") else 0)
        except Exception as exc:
            yield FileRecord(
                relative_path=str(rel),
                language=language,
                file_kind="source",
                size_bytes=size,
                line_count=0,
                included=False,
                skip_reason=f"read_error:{exc}",
            )
            continue

        # Generated file detection: scan header region only
        header = text[:_GENERATED_HEADER_BYTES]
        if any(marker in header for marker in _GENERATED_MARKERS):
            yield FileRecord(
                relative_path=str(rel),
                language=language,
                file_kind="generated",
                size_bytes=size,
                line_count=line_count,
                included=False,
                skip_reason="generated_file",
            )
            continue

        file_kind = _classify_file_kind(str(rel), language)

        yield FileRecord(
            relative_path=str(rel),
            language=language,
            file_kind=file_kind,
            size_bytes=size,
            line_count=line_count,
            included=True,
            skip_reason=None,
        )


def _classify_file_kind(relative_path: str, language: str) -> str:
    path_lower = relative_path.lower()
    if language in ("markdown", "rst", "text"):
        return "doc"
    if language in ("yaml", "toml", "json", "ini", "xml", "dockerfile", "makefile", "terraform", "hcl"):
        return "config"
    if language in ("shell",):
        return "script"
    if any(p in path_lower for p in ("test/", "tests/", "spec/", "specs/", "__tests__")):
        return "test"
    return "source"


# ---------------------------------------------------------------------------
# Chunk extraction
# ---------------------------------------------------------------------------

def extract_chunks(repo_path: Path, file_record: FileRecord) -> list[Chunk]:
    """Extract chunks from a single included file. Returns empty list on error."""
    if not file_record.included:
        return []

    abs_path = repo_path / file_record.relative_path
    try:
        text = abs_path.read_text(encoding="utf-8", errors="replace")
    except Exception as exc:
        logger.warning("Cannot read %s: %s", file_record.relative_path, exc)
        return []

    lines = text.splitlines()
    lang = file_record.language or ""

    try:
        if lang == "python":
            return _extract_python_chunks(text, lines, file_record.relative_path)
        elif lang in ("javascript", "typescript"):
            return _extract_js_ts_chunks(lines, file_record.relative_path, lang)
        elif lang == "rust":
            return _extract_rust_chunks(lines, file_record.relative_path)
        elif lang in ("markdown", "rst"):
            return _extract_doc_chunks(lines, file_record.relative_path, lang)
        else:
            return _extract_fallback_chunks(lines, file_record.relative_path, lang)
    except Exception as exc:
        logger.warning("Extraction failed for %s: %s", file_record.relative_path, exc)
        return _extract_fallback_chunks(lines, file_record.relative_path, lang)


# --- Python ---

_PY_CLASS_DEF = re.compile(r"^(class\s+(\w+))")
_PY_FUNC_DEF = re.compile(r"^((?:async\s+)?def\s+(\w+))")
_PY_DECORATED = re.compile(r"^@")


def _extract_python_chunks(text: str, lines: list[str], file_path: str) -> list[Chunk]:
    """Primary Python extractor. Uses AST for symbol boundaries; falls back to regex on parse error."""
    specs = extract_python_ast(text, file_path)
    if specs:
        return _ast_specs_to_chunks(specs, lines, file_path)
    return _extract_python_chunks_regex(lines, file_path)


def _ast_specs_to_chunks(specs: list[ASTChunkSpec], lines: list[str], file_path: str) -> list[Chunk]:
    """Convert ASTChunkSpec list to Chunk list. Falls back to whole-file chunk if all specs yield empty content."""
    chunks: list[Chunk] = []
    for spec in specs:
        _add_chunk(
            chunks, lines,
            spec.start_line - 1,  # _add_chunk uses 0-indexed
            spec.end_line - 1,
            file_path, spec.chunk_type, spec.symbol_name, "python",
        )
    if not chunks:
        return _whole_file_chunk(lines, file_path, "python")
    return chunks


def _extract_python_chunks_regex(lines: list[str], file_path: str) -> list[Chunk]:
    """Regex-based fallback Python extractor. Used when AST parsing fails."""
    chunks: list[Chunk] = []
    i = 0
    n = len(lines)

    while i < n:
        line = lines[i]
        m = _PY_CLASS_DEF.match(line) or _PY_FUNC_DEF.match(line)

        if not m:
            if _PY_DECORATED.match(line.strip()):
                j = i + 1
                while j < n and (_PY_DECORATED.match(lines[j].strip()) or not lines[j].strip()):
                    j += 1
                if j < n:
                    m = _PY_CLASS_DEF.match(lines[j]) or _PY_FUNC_DEF.match(lines[j])
                    if m:
                        symbol = m.group(2)
                        chunk_type = "class" if "class" in lines[j] else "function"
                        end = _find_python_block_end(lines, j)
                        _add_chunk(chunks, lines, i, end, file_path, chunk_type, symbol, "python")
                        i = end + 1
                        continue
            i += 1
            continue

        symbol = m.group(2)
        chunk_type = "class" if "class" in line else "function"
        end = _find_python_block_end(lines, i)
        _add_chunk(chunks, lines, i, end, file_path, chunk_type, symbol, "python")
        i = end + 1

    if not chunks:
        return _whole_file_chunk(lines, file_path, "python")
    return chunks


def _find_python_block_end(lines: list[str], start: int) -> int:
    """Find the end line of a Python indented block."""
    n = len(lines)
    if start >= n:
        return start

    first_line = lines[start]
    base_indent = len(first_line) - len(first_line.lstrip())

    i = start + 1
    last_content = start
    while i < n:
        line = lines[i]
        stripped = line.strip()
        if not stripped:
            i += 1
            continue
        indent = len(line) - len(line.lstrip())
        if indent <= base_indent and i > start:
            break
        last_content = i
        i += 1
    return last_content


# --- JS / TS ---

_JS_FUNCTION = re.compile(
    r"^(?:export\s+)?(?:default\s+)?(?:async\s+)?function\s+(\w+)"
    r"|^(?:export\s+)?(?:const|let|var)\s+(\w+)\s*=\s*(?:async\s*)?\("
    r"|^(?:export\s+)?(?:const|let|var)\s+(\w+)\s*=\s*(?:async\s*)?function"
)
_JS_CLASS = re.compile(r"^(?:export\s+)?(?:default\s+)?class\s+(\w+)")
_JS_ARROW = re.compile(r"^(?:export\s+)?(?:const|let|var)\s+(\w+)\s*=\s*(?:async\s*)?\(.*\)\s*=>")


def _extract_js_ts_chunks(lines: list[str], file_path: str, lang: str) -> list[Chunk]:
    chunks: list[Chunk] = []
    i = 0
    n = len(lines)
    brace_depth = 0

    while i < n:
        line = lines[i].strip()

        m_class = _JS_CLASS.match(line)
        m_func = _JS_FUNCTION.match(line) or _JS_ARROW.match(line)

        if m_class:
            symbol = m_class.group(1)
            end = _find_brace_block_end(lines, i)
            _add_chunk(chunks, lines, i, end, file_path, "class", symbol, lang)
            i = end + 1
            continue

        if m_func:
            groups = m_func.groups()
            symbol = next((g for g in groups if g), "anonymous")
            end = _find_brace_block_end(lines, i)
            _add_chunk(chunks, lines, i, end, file_path, "function", symbol, lang)
            i = end + 1
            continue

        i += 1

    if not chunks:
        return _whole_file_chunk(lines, file_path, lang)
    return chunks


def _find_brace_block_end(lines: list[str], start: int) -> int:
    """Find end of a { } delimited block."""
    n = len(lines)
    depth = 0
    found_open = False
    for i in range(start, n):
        for ch in lines[i]:
            if ch == "{":
                depth += 1
                found_open = True
            elif ch == "}":
                depth -= 1
                if found_open and depth <= 0:
                    return i
    return n - 1


# --- Rust ---

_RUST_FN = re.compile(r"^(?:pub\s+)?(?:async\s+)?fn\s+(\w+)")
_RUST_STRUCT = re.compile(r"^(?:pub\s+)?struct\s+(\w+)")
_RUST_IMPL = re.compile(r"^(?:pub\s+)?impl(?:<[^>]*>)?\s+(\w+)")
_RUST_ENUM = re.compile(r"^(?:pub\s+)?enum\s+(\w+)")
_RUST_TRAIT = re.compile(r"^(?:pub\s+)?trait\s+(\w+)")


def _extract_rust_chunks(lines: list[str], file_path: str) -> list[Chunk]:
    chunks: list[Chunk] = []
    i = 0
    n = len(lines)

    while i < n:
        stripped = lines[i].strip()

        for pattern, chunk_type in [
            (_RUST_FN, "function"),
            (_RUST_STRUCT, "struct"),
            (_RUST_IMPL, "impl"),
            (_RUST_ENUM, "enum"),
            (_RUST_TRAIT, "trait"),
        ]:
            m = pattern.match(stripped)
            if m:
                symbol = m.group(1)
                end = _find_brace_block_end(lines, i)
                _add_chunk(chunks, lines, i, end, file_path, chunk_type, symbol, "rust")
                i = end + 1
                break
        else:
            i += 1

    if not chunks:
        return _whole_file_chunk(lines, file_path, "rust")
    return chunks


# --- Markdown / RST ---

_MD_HEADING = re.compile(r"^#{1,6}\s+(.+)")
_MD_FENCE_START = re.compile(r"^```(\w*)")
_RST_HEADING_CHARS = set("=-~^*+#`'\"!$%&<>?@\\|/")


def _extract_doc_chunks(lines: list[str], file_path: str, lang: str) -> list[Chunk]:
    chunks: list[Chunk] = []
    n = len(lines)
    section_start = 0
    section_title: str | None = None
    in_fence = False
    fence_start = 0
    fence_lang: str | None = None

    def flush(end: int) -> None:
        if end > section_start:
            _add_chunk(chunks, lines, section_start, end - 1, file_path, "section", section_title, lang)

    i = 0
    while i < n:
        line = lines[i]

        # Fenced code-block detection (markdown only)
        if lang == "markdown":
            m_fence = _MD_FENCE_START.match(line)
            if m_fence:
                if not in_fence:
                    in_fence = True
                    fence_start = i
                    hint = m_fence.group(1)
                    fence_lang = hint if hint else None
                else:
                    _add_chunk(chunks, lines, fence_start, i, file_path, "code_block", fence_lang, lang)
                    in_fence = False
                    fence_lang = None
                i += 1
                continue

        if not in_fence:
            m = _MD_HEADING.match(line)
            if m and lang == "markdown":
                flush(i)
                section_start = i
                section_title = m.group(1).strip()
            elif lang == "rst" and i + 1 < n:
                underline = lines[i + 1].strip()
                if underline and all(c in _RST_HEADING_CHARS for c in underline) and len(underline) >= len(line.strip()):
                    flush(i)
                    section_start = i
                    section_title = line.strip()
        i += 1

    # If a fence was never closed, emit whatever was captured as a partial block
    if in_fence:
        logger.debug("Unclosed code fence in %s at line %d", file_path, fence_start + 1)
        _add_chunk(chunks, lines, fence_start, n - 1, file_path, "code_block", fence_lang, lang)

    flush(n)

    if not chunks:
        return _whole_file_chunk(lines, file_path, lang)
    return chunks


# --- Fallback (fixed sections) ---

FALLBACK_SECTION_LINES = 60
FALLBACK_MIN_LINES = 10


def _extract_fallback_chunks(lines: list[str], file_path: str, lang: str) -> list[Chunk]:
    if len(lines) < FALLBACK_MIN_LINES:
        return _whole_file_chunk(lines, file_path, lang)

    chunks: list[Chunk] = []
    n = len(lines)
    i = 0
    section = 0
    while i < n:
        end = min(i + FALLBACK_SECTION_LINES - 1, n - 1)
        _add_chunk(chunks, lines, i, end, file_path, "section", f"section_{section}", lang)
        section += 1
        i = end + 1
    return chunks


# --- Helpers ---

def _add_chunk(
    chunks: list[Chunk],
    lines: list[str],
    start: int,
    end: int,
    file_path: str,
    chunk_type: str,
    symbol_name: str | None,
    language: str,
) -> None:
    content = "\n".join(lines[start : end + 1])
    if not content.strip():
        return
    chunks.append(Chunk(
        file_path=file_path,
        language=language,
        chunk_type=chunk_type,
        symbol_name=symbol_name,
        start_line=start + 1,   # 1-indexed
        end_line=end + 1,
        content=content,
    ))


def _whole_file_chunk(lines: list[str], file_path: str, lang: str) -> list[Chunk]:
    content = "\n".join(lines)
    if not content.strip():
        return []
    return [Chunk(
        file_path=file_path,
        language=lang,
        chunk_type="file",
        symbol_name=None,
        start_line=1,
        end_line=len(lines),
        content=content,
    )]


# ---------------------------------------------------------------------------
# DB persistence helpers
# ---------------------------------------------------------------------------

def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def store_file_record(
    conn: sqlite3.Connection,
    snapshot_id: int,
    repo_id: int,
    file_record: FileRecord,
) -> int:
    cursor = conn.execute(
        """INSERT INTO files
           (snapshot_id, repo_id, relative_path, language, file_kind,
            size_bytes, line_count, included, skip_reason, inspected_at)
           VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
        (
            snapshot_id,
            repo_id,
            file_record.relative_path,
            file_record.language,
            file_record.file_kind,
            file_record.size_bytes,
            file_record.line_count,
            1 if file_record.included else 0,
            file_record.skip_reason,
            _now(),
        ),
    )
    return cursor.lastrowid


def store_chunk(
    conn: sqlite3.Connection,
    file_id: int,
    snapshot_id: int,
    repo_id: int,
    chunk: Chunk,
    classification: dict,
) -> int:
    import json
    cursor = conn.execute(
        """INSERT INTO chunks
           (file_id, snapshot_id, repo_id, chunk_type, symbol_name,
            start_line, end_line, content_hash, language,
            longevity_band, longevity_confidence,
            primary_tag, summary, quality_flags, extracted_at,
            difficulty, topic, subtopic, style, paradigm, architecture_level,
            security_relevance, example_type, beginner_safe,
            chunk_quality_score, teaching_value_score)
           VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
        (
            file_id,
            snapshot_id,
            repo_id,
            chunk.chunk_type,
            chunk.symbol_name,
            chunk.start_line,
            chunk.end_line,
            chunk.content_hash,
            chunk.language,
            classification.get("longevity_band", "small"),
            classification.get("longevity_confidence", 0.0),
            classification.get("primary_tag"),
            classification.get("summary"),
            json.dumps(classification.get("quality_flags", [])),
            _now(),
            classification.get("difficulty"),
            classification.get("topic"),
            classification.get("subtopic"),
            classification.get("style"),
            classification.get("paradigm"),
            classification.get("architecture_level"),
            classification.get("security_relevance"),
            classification.get("example_type"),
            classification.get("beginner_safe"),
            classification.get("chunk_quality_score"),
            classification.get("teaching_value_score"),
        ),
    )
    return cursor.lastrowid


def store_chunk_tags(
    conn: sqlite3.Connection,
    chunk_id: int,
    tags: list[str],
    tag_source: str = "heuristic",
) -> None:
    for tag in tags:
        conn.execute(
            "INSERT INTO chunk_tags (chunk_id, tag, tag_source) VALUES (?, ?, ?)",
            (chunk_id, tag, tag_source),
        )
