"""Validation, deduplication, and quarantine for extracted chunks."""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass, field
from pathlib import Path

from ..database import get_connection

logger = logging.getLogger(__name__)

# Quarantine reason constants
REASON_EXACT_DUPLICATE = "exact_duplicate"
REASON_BOILERPLATE = "boilerplate"
REASON_PLACEHOLDER = "placeholder"
REASON_LICENSE_HEADER = "license_header"
REASON_GENERATED_MARKER = "generated_marker"

# Cheap content-based heuristics: license header prefixes (lowercased, stripped)
_LICENSE_PREFIXES = (
    "# mit license",
    "# copyright",
    "# spdx-license-identifier",
    "/* copyright",
    "// copyright",
    "-- copyright",
    "# license:",
    "# this file is part of",
)

# Cheap content-based heuristics: generated-file markers
_GENERATED_MARKERS = (
    "# this file is auto-generated",
    "# do not edit",
    "# do not modify",
    "// generated by",
    "// code generated",
    "/* do not edit",
    "# generated by",
    "autogenerated file",
)


@dataclass
class ValidationReport:
    """Summary returned by validate_pending_chunks()."""
    snapshot_id: int | None
    pending_count: int
    accepted: int = 0
    quarantined: int = 0
    by_reason: dict[str, int] = field(default_factory=dict)
    errors: list[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "snapshot_id": self.snapshot_id,
            "pending_count": self.pending_count,
            "accepted": self.accepted,
            "quarantined": self.quarantined,
            "by_reason": self.by_reason,
            "errors": self.errors,
        }


def validate_pending_chunks(
    db_path: Path | None = None,
    snapshot_id: int | None = None,
) -> ValidationReport:
    """
    Validate all pending chunks, optionally scoped to a single snapshot.

    Only processes chunks with validation_status='pending' — idempotent by design.
    Exact-duplicate detection compares content_hash against all non-quarantined chunks
    in the DB, so duplicates across different repos are caught.

    Quarantine checks (first match wins):
      1. exact_duplicate  — same content_hash exists elsewhere in the DB
      2. boilerplate      — very_short + mostly_comments quality flags both set
      3. placeholder      — has_placeholder quality flag set
      4. license_header   — content starts with a known license prefix (if readable)
      5. generated_marker — content contains a generated-file marker (if readable)

    Returns a ValidationReport with counts and per-reason breakdown.
    """
    conn = get_connection(db_path)
    report = ValidationReport(snapshot_id=snapshot_id, pending_count=0)

    try:
        if snapshot_id is not None:
            rows = conn.execute(
                """SELECT chunk_id, content_hash, quality_flags,
                          longevity_band, primary_tag
                   FROM chunks
                   WHERE validation_status = 'pending' AND snapshot_id = ?""",
                (snapshot_id,),
            ).fetchall()
        else:
            rows = conn.execute(
                """SELECT chunk_id, content_hash, quality_flags,
                          longevity_band, primary_tag
                   FROM chunks
                   WHERE validation_status = 'pending'""",
            ).fetchall()

        report.pending_count = len(rows)
        if not rows:
            return report

        for row in rows:
            chunk_id = row["chunk_id"]
            content_hash = row["content_hash"]
            try:
                flags = json.loads(row["quality_flags"] or "[]")
            except (ValueError, TypeError):
                flags = []

            quarantine_reason = _classify_chunk(
                conn, chunk_id, content_hash, flags,
                row["longevity_band"], row["primary_tag"],
            )

            if quarantine_reason:
                try:
                    conn.execute(
                        "UPDATE chunks SET validation_status='quarantined', quarantine_reason=? WHERE chunk_id=?",
                        (quarantine_reason, chunk_id),
                    )
                    conn.commit()
                    report.quarantined += 1
                    report.by_reason[quarantine_reason] = (
                        report.by_reason.get(quarantine_reason, 0) + 1
                    )
                    from .storage import write_quarantine_artifact
                    write_quarantine_artifact(chunk_id, content_hash, quarantine_reason)
                except Exception as exc:
                    logger.warning("Failed to quarantine chunk %d: %s", chunk_id, exc)
                    report.errors.append(f"chunk {chunk_id}: {exc}")
            else:
                try:
                    conn.execute(
                        "UPDATE chunks SET validation_status='accepted' WHERE chunk_id=?",
                        (chunk_id,),
                    )
                    conn.commit()
                    report.accepted += 1
                except Exception as exc:
                    logger.warning("Failed to accept chunk %d: %s", chunk_id, exc)
                    report.errors.append(f"chunk {chunk_id}: {exc}")

    except Exception as exc:
        logger.error("Validation pipeline error: %s", exc)
        report.errors.append(str(exc))
    finally:
        conn.close()

    logger.info(
        "Validation complete (snapshot=%s): %d pending → %d accepted, %d quarantined, %d errors",
        snapshot_id, report.pending_count, report.accepted, report.quarantined, len(report.errors),
    )
    return report


def get_validation_summary(db_path: Path | None = None) -> dict:
    """Return aggregate validation stats across all chunks."""
    conn = get_connection(db_path)
    try:
        total = conn.execute("SELECT COUNT(*) as cnt FROM chunks").fetchone()["cnt"]
        status_rows = conn.execute(
            "SELECT validation_status, COUNT(*) as cnt FROM chunks GROUP BY validation_status"
        ).fetchall()
        reason_rows = conn.execute(
            """SELECT quarantine_reason, COUNT(*) as cnt FROM chunks
               WHERE validation_status = 'quarantined' AND quarantine_reason IS NOT NULL
               GROUP BY quarantine_reason"""
        ).fetchall()
        pending = conn.execute(
            "SELECT COUNT(*) as cnt FROM chunks WHERE validation_status = 'pending'"
        ).fetchone()["cnt"]
        return {
            "total_chunks": total,
            "pending_chunks": pending,
            "by_status": {r["validation_status"]: r["cnt"] for r in status_rows},
            "quarantine_by_reason": {r["quarantine_reason"]: r["cnt"] for r in reason_rows},
        }
    finally:
        conn.close()


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _classify_chunk(
    conn,
    chunk_id: int,
    content_hash: str,
    flags: list[str],
    longevity_band: str | None,
    primary_tag: str | None,
) -> str | None:
    """Return a quarantine reason string, or None to accept the chunk."""

    # 1. Exact duplicate — cross-repo
    if _is_exact_duplicate(conn, content_hash, chunk_id):
        return REASON_EXACT_DUPLICATE

    # 2. Boilerplate: very_short + mostly_comments
    if "very_short" in flags and "mostly_comments" in flags:
        return REASON_BOILERPLATE

    # 3. Placeholder content
    if "has_placeholder" in flags:
        return REASON_PLACEHOLDER

    # 4 & 5. Cheap content-based heuristics (skipped gracefully if unreadable)
    content = _read_chunk_content(chunk_id, longevity_band, primary_tag)
    if content:
        content_lower = content.lower().strip()
        if any(content_lower.startswith(p) for p in _LICENSE_PREFIXES):
            return REASON_LICENSE_HEADER
        if any(m in content_lower for m in _GENERATED_MARKERS):
            return REASON_GENERATED_MARKER

    return None


def _is_exact_duplicate(conn, content_hash: str, chunk_id: int) -> bool:
    """Return True if a non-quarantined chunk with the same hash already exists."""
    row = conn.execute(
        """SELECT 1 FROM chunks
           WHERE content_hash = ?
             AND chunk_id != ?
             AND validation_status != 'quarantined'
           LIMIT 1""",
        (content_hash, chunk_id),
    ).fetchone()
    return row is not None


def _read_chunk_content(
    chunk_id: int,
    longevity_band: str | None,
    primary_tag: str | None,
) -> str | None:
    """
    Try to read chunk content from its curated artifact file.
    Returns None if the file cannot be found or read (non-fatal).
    """
    try:
        from .manifests import EXTRACTED_DIR, _safe_name, VALID_BANDS
        band = longevity_band if longevity_band in VALID_BANDS else "small"
        tag = _safe_name(primary_tag or "general")
        tag_dir = EXTRACTED_DIR / band / tag
        if not tag_dir.exists():
            return None
        # Artifact filenames include the chunk_id: {safe_repo}_{snap}_{chunk_id}_{sym}.txt
        matches = list(tag_dir.glob(f"*_{chunk_id}_*.txt"))
        if not matches:
            return None
        text = matches[0].read_text(encoding="utf-8", errors="replace")
        # Strip provenance header: --- \n {JSON} \n --- \n\n {content}
        parts = text.split("---", 2)
        if len(parts) >= 3:
            return parts[2].strip()
        return text
    except Exception:
        return None
